2025-06-18T10:00:47.1608854Z ##[group]Run python -m pip install --upgrade pip
2025-06-18T10:00:47.1609267Z [36;1mpython -m pip install --upgrade pip[0m
2025-06-18T10:00:47.1609565Z [36;1mpip install -e .[dev][0m
2025-06-18T10:00:47.1710346Z shell: /usr/bin/bash -e {0}
2025-06-18T10:00:47.1710604Z env:
2025-06-18T10:00:47.1710870Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
2025-06-18T10:00:47.1711278Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
2025-06-18T10:00:47.1711678Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
2025-06-18T10:00:47.1712012Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
2025-06-18T10:00:47.1712358Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
2025-06-18T10:00:47.1712700Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
2025-06-18T10:00:47.1712996Z ##[endgroup]
2025-06-18T10:00:47.5413498Z Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (25.0.1)
2025-06-18T10:00:48.1023003Z Obtaining file:///home/runner/work/Automatizacion_RSI_PCI/Automatizacion_RSI_PCI
2025-06-18T10:00:48.1058875Z ERROR: Exception:
2025-06-18T10:00:48.1059306Z Traceback (most recent call last):
2025-06-18T10:00:48.1068109Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 106, in _run_wrapper
2025-06-18T10:00:48.1069074Z     status = _inner_run()
2025-06-18T10:00:48.1069976Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 97, in _inner_run
2025-06-18T10:00:48.1070894Z     return self.run(options, args)
2025-06-18T10:00:48.1071777Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
2025-06-18T10:00:48.1072635Z     return func(self, options, args)
2025-06-18T10:00:48.1073481Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 386, in run
2025-06-18T10:00:48.1074349Z     requirement_set = resolver.resolve(
2025-06-18T10:00:48.1075478Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
2025-06-18T10:00:48.1076533Z     collected = self.factory.collect_root_requirements(root_reqs)
2025-06-18T10:00:48.1077729Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 545, in collect_root_requirements
2025-06-18T10:00:48.1078748Z     reqs = list(
2025-06-18T10:00:48.1079769Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 501, in _make_requirements_from_install_req
2025-06-18T10:00:48.1080871Z     cand = self._make_base_candidate_from_link(
2025-06-18T10:00:48.1081974Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 212, in _make_base_candidate_from_link
2025-06-18T10:00:48.1083435Z     self._editable_candidate_cache[link] = EditableCandidate(
2025-06-18T10:00:48.1084527Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 329, in __init__
2025-06-18T10:00:48.1085757Z     super().__init__(
2025-06-18T10:00:48.1086673Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
2025-06-18T10:00:48.1087625Z     self.dist = self._prepare()
2025-06-18T10:00:48.1088551Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 236, in _prepare
2025-06-18T10:00:48.1089544Z     dist = self._prepare_distribution()
2025-06-18T10:00:48.1090614Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 339, in _prepare_distribution
2025-06-18T10:00:48.1168927Z     return self._factory.preparer.prepare_editable_requirement(self._ireq)
2025-06-18T10:00:48.1170338Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 698, in prepare_editable_requirement
2025-06-18T10:00:48.1171487Z     dist = _get_prepared_distribution(
2025-06-18T10:00:48.1172523Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
2025-06-18T10:00:48.1173497Z     abstract_dist.prepare_distribution_metadata(
2025-06-18T10:00:48.1174592Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 39, in prepare_distribution_metadata
2025-06-18T10:00:48.1175782Z     self.req.load_pyproject_toml()
2025-06-18T10:00:48.1176709Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 512, in load_pyproject_toml
2025-06-18T10:00:48.1177653Z     pyproject_toml_data = load_pyproject_toml(
2025-06-18T10:00:48.1178606Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 70, in load_pyproject_toml
2025-06-18T10:00:48.1179513Z     pp_toml = tomllib.loads(f.read())
2025-06-18T10:00:48.1180365Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_vendor/tomli/_parser.py", line 180, in loads
2025-06-18T10:00:48.1181298Z     pos = key_value_rule(src, pos, out, header, parse_float)
2025-06-18T10:00:48.1182352Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_vendor/tomli/_parser.py", line 408, in key_value_rule
2025-06-18T10:00:48.1183359Z     pos, key, value = parse_key_value_pair(src, pos, parse_float, nest_lvl=0)
2025-06-18T10:00:48.1184435Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_vendor/tomli/_parser.py", line 451, in parse_key_value_pair
2025-06-18T10:00:48.1185576Z     pos, value = parse_value(src, pos, parse_float, nest_lvl)
2025-06-18T10:00:48.1186537Z   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pip/_vendor/tomli/_parser.py", line 745, in parse_value
2025-06-18T10:00:48.1187468Z     raise TOMLDecodeError("Invalid value", src, pos)
2025-06-18T10:00:48.1188085Z pip._vendor.tomli._parser.TOMLDecodeError: Invalid value (at line 6, column 17)
2025-06-18T10:00:48.1506508Z ##[error]Process completed with exit code 2.
